config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :prices
  resources :cars
  resources :booths
  devise_for :users
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/booth.rb
class Booth < ApplicationRecord
end

app/controllers/booths_controller.rb
class BoothsController < ApplicationController
  before_action :set_booth, only: %i[ show edit update destroy ]

  # GET /booths or /booths.json
  def index
    @booths = Booth.all
  end

  # GET /booths/1 or /booths/1.json
  def show
  end

  # GET /booths/new
  def new
    @booth = Booth.new
  end

  # GET /booths/1/edit
  def edit
  end

  # POST /booths or /booths.json
  def create
    @booth = Booth.new(booth_params)

    respond_to do |format|
      if @booth.save
        format.html { redirect_to @booth, notice: "Booth was successfully created." }
        format.json { render :show, status: :created, location: @booth }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booth.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /booths/1 or /booths/1.json
  def update
    respond_to do |format|
      if @booth.update(booth_params)
        format.html { redirect_to @booth, notice: "Booth was successfully updated." }
        format.json { render :show, status: :ok, location: @booth }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booth.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /booths/1 or /booths/1.json
  def destroy
    @booth.destroy
    respond_to do |format|
      format.html { redirect_to booths_url, notice: "Booth was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booth
      @booth = Booth.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booth_params
      params.require(:booth).permit(:name)
    end
end

app/helpers/booths_helper.rb
module BoothsHelper
end

app/views/booths/_form.html.erb
<%= form_with(model: booth) do |form| %>
  <% if booth.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booth.errors.count, "error") %> prohibited this booth from being saved:</h2>

      <ul>
        <% booth.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/booths/edit.html.erb
<h1>Editing Booth</h1>

<%= render 'form', booth: @booth %>

<%= link_to 'Show', @booth %> |
<%= link_to 'Back', booths_path %>

app/views/booths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Booths</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @booths.each do |booth| %>
      <tr>
        <td><%= booth.name %></td>
        <td><%= link_to 'Show', booth %></td>
        <td><%= link_to 'Edit', edit_booth_path(booth) %></td>
        <td><%= link_to 'Destroy', booth, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booth', new_booth_path %>

app/views/booths/new.html.erb
<h1>New Booth</h1>

<%= render 'form', booth: @booth %>

<%= link_to 'Back', booths_path %>

app/views/booths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @booth.name %>
</p>

<%= link_to 'Edit', edit_booth_path(@booth) %> |
<%= link_to 'Back', booths_path %>