config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :prices
  resources :cars
  resources :booths
  devise_for :users
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :car
  has_many :payments

  before_destroy {|record|
    if record.payments.length > 0
      throw(:abort)
    end
  }
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_price, only: %i[ show edit update destroy ]

  # GET /prices or /prices.json
  def index
    @prices = Price.all
  end

  # GET /prices/1 or /prices/1.json
  def show
  end

  # GET /prices/new
  def new
    @price = Price.new
    @cars = Car.all
  end

  # GET /prices/1/edit
  def edit
    @cars = Car.all
  end

  # POST /prices or /prices.json
  def create
    @price = Price.new(price_params)

    respond_to do |format|
      if @price.save
        format.html { redirect_to @price, notice: "Price was successfully created." }
        format.json { render :show, status: :created, location: @price }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prices/1 or /prices/1.json
  def update
    respond_to do |format|
      if @price.update(price_params)
        format.html { redirect_to @price, notice: "Price was successfully updated." }
        format.json { render :show, status: :ok, location: @price }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prices/1 or /prices/1.json
  def destroy
    @price.destroy
    respond_to do |format|
      format.html { redirect_to prices_url, notice: "Price was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price
      @price = Price.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def price_params
      params.require(:price).permit(:car_id, :from, :to, :amount)
    end
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/prices/_form.html.erb
<%= form_with(model: price) do |form| %>
  <% if price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(price.errors.count, "error") %> prohibited this price from being saved:</h2>

      <ul>
        <% price.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :car_id %>
    <%= form.collection_select :car_id, @cars, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :from %>
    <%= form.date_select :from %>
  </div>

  <div class="field">
    <%= form.label :to %>
    <%= form.date_select :to %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/prices/edit.html.erb
<h1>Editing Price</h1>

<%= render 'form', price: @price %>

<%= link_to 'Show', @price %> |
<%= link_to 'Back', prices_path %>

app/views/prices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prices</h1>

<table>
  <thead>
    <tr>
      <th>Car</th>
      <th>From</th>
      <th>To</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prices.each do |price| %>
      <tr>
        <td><%= price.car_id %></td>
        <td><%= price.from %></td>
        <td><%= price.to %></td>
        <td><%= price.amount %></td>
        <td><%= link_to 'Show', price %></td>
        <td><%= link_to 'Edit', edit_price_path(price) %></td>
        <td><%= link_to 'Destroy', price, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Price', new_price_path %>

app/views/prices/new.html.erb
<h1>New Price</h1>

<%= render 'form', price: @price %>

<%= link_to 'Back', prices_path %>

app/views/prices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Car:</strong>
  <%= @price.car_id %>
</p>

<p>
  <strong>From:</strong>
  <%= @price.from %>
</p>

<p>
  <strong>To:</strong>
  <%= @price.to %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @price.amount %>
</p>

<%= link_to 'Edit', edit_price_path(@price) %> |
<%= link_to 'Back', prices_path %>